# Generated by Django 3.1.4 on 2020-12-27 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CharacterAttributes',
            fields=[
                (
                    'character', models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to='wwwhero.character'
                    )
                ),
                ('max_hp', models.IntegerField(default=10)),
                ('hp', models.IntegerField(default=10)),
                ('dmg', models.IntegerField(default=1)),
                ('luck', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Character Attributes',
            },
        ),
    ]
