# Generated by Django 3.1.4 on 2020-12-31 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('wwwhero', '0002_uservisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterSelection',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('character', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='wwwhero.character')),
            ],
        ),
    ]
