# Generated by Django 3.1.4 on 2021-01-05 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wwwhero', '0003_characterselection'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterCooldown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Level', 'Level'), ('Skill', 'Skill')], default='Level', max_length=5)),
                ('until', models.DateTimeField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wwwhero.character')),
            ],
        ),
    ]
