# Generated by Django 3.1.4 on 2021-01-06 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wwwhero', '0004_charactercooldown'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characterattributes',
            options={'verbose_name_plural': 'Character attributes'},
        ),
        migrations.AlterUniqueTogether(
            name='charactercooldown',
            unique_together={('type', 'character')},
        ),
    ]
