# Generated by Django 3.1.4 on 2021-01-09 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wwwhero', '0005_auto_20210106_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='characterselection',
            name='character',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wwwhero.character'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='bg/location')),
                ('min_level', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=False)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wwwhero.locationtype')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterLocation',
            fields=[
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wwwhero.character')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wwwhero.location')),
            ],
        ),
    ]
