# Generated by Django 3.2.7 on 2021-09-19 17:00

from django.db import migrations, models
import django.db.models.deletion

from wwwhero.models import Character, Inventory, ItemBlueprint


def create_gold(apps, schema_editor):
    ItemBlueprint.objects.create(
        item_type=ItemBlueprint.ItemType.GOLD,
        slot_type=ItemBlueprint.SlotType.INVENTORY,
        is_stackable=True,
        name="gold",
        description="Shiny coins!",
    )


def init_inventory(apps, schema_editor):
    chars = Character.objects.all()
    for ch in chars:
        Inventory.objects.create(
            character=ch,
            max_space=Inventory.max_space.field.default + ch.level - 1
        )


class Migration(migrations.Migration):

    dependencies = [
        ('wwwhero', '0006_auto_20210109_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_space', models.PositiveSmallIntegerField(default=20)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wwwhero.character')),
            ],
        ),
        migrations.CreateModel(
            name='ItemBlueprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.PositiveSmallIntegerField(choices=[(1, 'Armor'), (2, 'Junk'), (3, 'Gold'), (4, 'Quest'), (5, 'Weapon')])),
                ('slot_type', models.PositiveSmallIntegerField(choices=[(1, 'Head'), (2, 'Breast'), (3, 'Legs'), (4, 'Left arm'), (5, 'Right arm'), (6, 'Boots'), (7, 'Inventory')])),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('is_consumable', models.BooleanField(default=False)),
                ('is_stackable', models.BooleanField(default=False)),
                ('is_droppable', models.BooleanField(default=False)),
                ('base_cost', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='charactercooldown',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Level'), (2, 'Skill'), (3, 'Search')], default=1),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('amount', models.PositiveSmallIntegerField(default=1)),
                ('rarity', models.PositiveSmallIntegerField(choices=[(1, 'Common'), (2, 'Uncommon'), (3, 'Rare'), (4, 'Epic'), (5, 'Legendary')])),
                ('min_damage', models.PositiveSmallIntegerField(default=0)),
                ('max_damage', models.PositiveSmallIntegerField(default=0)),
                ('defense', models.PositiveSmallIntegerField(default=0)),
                ('health', models.PositiveSmallIntegerField(default=0)),
                ('cost', models.PositiveSmallIntegerField(default=1)),
                ('skin', models.ImageField(blank=True, upload_to='skins/item')),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wwwhero.itemblueprint')),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wwwhero.inventory')),
            ],
        ),

        migrations.RunPython(init_inventory),
        migrations.RunPython(create_gold),
    ]
